version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: movielibrary
    ports:
      - "5432:5432"      # host:container
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
